---
version: '3.2'
services:
  mumble:
    build:
      context: './server'
    ports:
      - "64738:64738"
    restart: always
    volumes:
      - type: volume
        source: './data'
        target: '/opt/mumble'
        read_only: false
        volume:
          nocopy: false
    container_name: mumble-server
