---
version: '3'
services:
  mumble:
    build:
      context: './server'
    ports:
      - "64738:64738"
    restart: always
    volumes:
      - type: bind
        source: './data'
        target: '/opt/mumble'
        read_only: false
    container_name: mumble-server
    
